version: '3.9'
services:

  auction_service_db:
    hostname: auction_service_db
    container_name: auction_service_db
    image: postgres
    command: [ "postgres", "-c", "max_prepared_transactions=200" ]
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_DB_LOGIN}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB_PORT} -U $${POSTGRES_USER}" ]
      timeout: 2s
      retries: 15

  auction_service:
    container_name: auction_service
    restart: unless-stopped
    working_dir: /code/src
    command: uvicorn --log-level debug app.main:app --host $APP_HOST --port $APP_PORT --reload
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - auction_service_db
    environment:
      - POSTGRES_DB_LOGIN
      - POSTGRES_DB_PASSWORD
      - POSTGRES_DB_HOST
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_NAME
      - SQLALCHEMY_ECHO
      - SQLALCHEMY_POOL_SIZE
      - LOGGING_LEVEL
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./src:/code/src

